### ISSUE TITLE
question about "mlp.eval()"

### ISSUE THREAD

**Issue by BeierZhu** [linyongver/Bayesian-Invariant-Risk-Minmization#1]
Thanks for you excellent work. I have question about the line 217-218 in the [main.py](https://github.com/linyongver/Bayesian-Invariant-Risk-Minmization/blob/main/main.py)

```python
if flags.dataset != 'CifarMnist':
    mlp.eval()
```
why evaluating on CifarMnist does not set the model to eval mode?

**Comment by BeierZhu** [comment]
and when I set the eval mode for CifarMnist the test acc remains 50% during training, that is weird. Do you have any explanations? Thank you

**Comment by linyongver** [comment]
Dear BeierZhu:
    Thank you for your interest in Bayesian IRM. 
    This is because each image of CifarMnist is composed of two component: an image from MNIST and an image from Cifar. We found the normalization of  CifarMnist is quite strange. We tried BIRM and also the baselines (ERM, IRMv1, REx...) and found all these methods had 50%  test acc in the '.eval()' mode. So in this dataset, we didn't use '.eval()' model for all these methods  (BIRM and its baselines). We conjucture it is due to the ill behaved noramlization statistics of a concatenation of two distinct datasets. 
    The other two datasets (CMNIST and ColoredObject) are just fine.

**Comment by BeierZhu** [comment]
Dear Yong Lin:
 
I have tried combining the two images by addition instead of concatenation or change with resnet/vgg without bn, the strange phenomenon still exists. I am still figuring out why.

BIRM is an excellent work anyway. Thanks for you reply.

**Comment by linyongver** [comment]
Dear BeierZhu:
    If you are interested in this work (or my other works on IRM, see https://linyongver.github.io/Yong-Lin/ ). We can add a WeChat friend for further discussion. My account is: linyongver
   Best wishes.
   Yong Lin
