### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by liwq57** [linyongver/Bayesian-Invariant-Risk-Minmization#2]
作者请问代码中
flags.prior_sd_coef
表示什么呀，在代码中没有定义这个地方只有使用

**Comment by linyongver** [comment]
您好，谢谢对BIRM的关注。prior_sd_coef是一个对BIRM简化方法实现的参数。根据[1]中3.1.3的章节中的论述，classifier和feature extractor有两个自由度，所以可以将classifier的自由度fix住。然后在我们的BIRM[2]里面的Appendix B.2中，我们简化了BIRM的实现，也固定了classifier的Mean，然后将bayesian的分布的variance当成一个超参去调整。prior_sd_coef就是这个分布的variance。在utils，我们给每个数据集选了一个超参。
[1] Invariant Risk Minimization 
[2] Bayesian Invariant Risk Minimization

**Comment by linyongver** [comment]
如果没有更多问题，我先close这个issue，后续有问题可以发我邮件询问 ylindf@connect.ust.hk
